#_________________________
# Create a YAML file with Deployment details
#Let us now create the webserver.yaml file with the following content
#______________________________________
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: nginx:alpine
        ports:
        - containerPort: 80
